# Generated by Django 5.1.7 on 2025-06-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic Blue'), ('modern', 'Modern Green'), ('dark', 'Dark Mode')], default='modern', max_length=20),
        ),
    ]
