# Generated by Django 5.1.7 on 2025-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_resume_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
